//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepremsizHayat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERRORCODE
    {
        public int Id { get; set; }
        public int ResourceCode { get; set; }
        public string Message { get; set; }
        public string LanguageCode { get; set; }
    }
}
