//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepremsizHayat.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ACCOUNT
    {
        public int ACCOUNT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string E_MAIL { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<int> USER_ROLE_ID { get; set; }
        public string ACTIVATIONCODE { get; set; }
    }
}
